from django.urls import path
from . import views
from rest_framework.authtoken.views import ObtainAuthToken
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('doctor/all_orders/', views.OrderDetailViewDoc.as_view(),
         name='all_orders_doc'),
    path('laboratory/all_orders/',
         views.OrderDetailViewLab.as_view(), name='all_orders_lab'),
    path('delivery/all_orders/',
         views.OrderDetailViewDel.as_view(), name='all_orders_del'),
    path('create_order/', views.CreateOrderDetailView.as_view(), name='create_order'),
    path('delete_order/<int:pk>/',
         views.OrderDeleteView.as_view(), name='order_delete'),
    path('doctor/edit_order/<int:pk>/',
         views.OrderUpdateViewDoc.as_view(), name='order_edit_dac'),
    path('laboratory/edit_order/<int:pk>/',
         views.OrderUpdateViewLab.as_view(), name='order_edit_lab'),
    path('delivery/edit_order/<int:pk>/',
         views.OrderUpdateViewDel.as_view(), name='order_edit_del'),
    path('doctor/get_order/<int:order_id>/',
         views.OrderRetreiveViewDoc.as_view(), name='order_get_doc'),
    path('laboratory/get_order/<int:order_id>/',
         views.OrderRetreiveViewLab.as_view(), name='order_get_lab'),
    path('delivery/get_order/<int:order_id>/',
         views.OrderRetreiveViewDel.as_view(), name='order_get_del'),
    #     path('mark_as_delivered/',
    #          views.MarkAsDeliveredView.as_view(), name='mark_as_delivered'),
    path('create_user/', views.CreateUserDetailView.as_view(), name='create_user'),
    #     path('token/', ObtainAuthToken.as_view(), name='token_obtain'),
    #     path('signin/', views.SigninAPIView.as_view(), name='signin'),
    path('signin/', views.Signin, name='signin'),
    path('signout/', LogoutView.as_view(), name='signout'),
    #     path('test/', views.ProfileAPIView.as_view(), name='test'),
    path('laboratory/financials/',
         views.FinancialsDetailView.as_view(), name='financials'),
    path('delivery/financials/',
         views.DeliveryFinancialsDetailView.as_view(), name='delivery_financials'),
    path('get_or_create_contract/<int:pk>/',
         views.ContractRetrieveOrCreateView.as_view(), name='get_or_create_contract'),
    path('edit_contract/<int:pk>/',
         views.ContractUpdateView.as_view(), name='contract_edit'),
    #     path('get_csrf_token/', views.get_csrf_token, name='get_csrf_token'),
    path('lab_doctors/', views.LabDoctorsDetailView.as_view(), name='lab_doctors'),
    path('add_doctor/',
         views.SetLabToDoctorView.as_view(), name='add_doctor'),
    path('remove_doctor/',
         views.RemoveLabFromDoctorView.as_view(), name='remove_doctor'),
    path('delivery/check_lab_subscription/<int:lab_id>/',
         views.CheckLabSubscription.as_view(), name='order_get_del'),
    path('delivery/Change_lab_address/<int:lab_id>/',
         views.ChangeLabAddress.as_view(), name='Change_lab_address'),
    path('delivery/Change_doc_address/<int:lab_id>/',
         views.ChangeDocAddress.as_view(), name='Change_doc_address'),
    path('laboratory/toggle_subscription/',
         views.ToggleSubscription.as_view(), name='toggle_subscription'),
    path('laboratory/return_to_doc/<int:pk>/',
         views.ReturnToDoc.as_view(), name='return_to_doc'),
    path('laboratory/get_laboratory_profile/',
         views.GetLaboratoryProfile.as_view(), name='get_laboratory_profile'),
]

# path('test/<int:pk>/', views.OrderDetailView.as_view(), name='order'),
